version: '3'
services:
  web_discovery:
    build: ./web_discovery
    container_name: 'web_discovery'
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_OUTPUT: 'DiscoveredDomains'
      MESSAGES_PER_SECOND: 1000
      SEED: './data/products_seed.txt'
      NUMBER_RESULT_PAGES: 3
      SEARX_ADDRESS: 'http://searx:8888'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'DiscoveredDomains'
    external_links:
      - mongo
    volumes:
      - ./web_discovery/data:/data
      - ./web_discovery/src:/src

  domain_classifier:
    build: classifier_domain
    container_name: 'classifier_domain'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'DiscoveredDomains'
      TOPIC_OUTPUT: 'ClassifiedDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: '/data/training_set.csv'
      TRAINING_PARQUET: '/data/training_set.snappy.parquet'
      MODEL: '/model/classifier_domain.sav'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'ClassifiedDomains'
    restart: unless-stopped
    external_links:
      - mongo
    volumes:
      - ./classifier_domain/src:/src
      - ./classifier_domain/data:/data
      - ./classifier_domain/model:/model

  crawler_1:
    build: ./crawler
    container_name: 'crawler-1'
    environment:
      ID: '1'
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'CrawledDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    restart: unless-stopped
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_2:
    build: ./crawler
    container_name: 'crawler-2'
    environment:
      ID: '2'
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'CrawledDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    restart: unless-stopped
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_3:
    build: ./crawler
    container_name: 'crawler-3'
    environment:
      ID: '3'
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'CrawledDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    restart: unless-stopped
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_4:
    build: ./crawler
    container_name: 'crawler-4'
    environment:
      ID: '4'
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'CrawledDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    restart: unless-stopped
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_5:
    build: ./crawler
    container_name: 'crawler-5'
    environment:
      ID: '5'
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'CrawledDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    restart: unless-stopped
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  clusterizer:
    build: ./clusterizer
    container_name: 'clusterizer'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'CrawledDomains'
      TOPIC_OUTPUT: 'ClusterizedDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      MIN_SIZE_CLUSTER: 20
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE_READ: 'CrawledPages'
      DATABASE_WRITE: 'ClusterizedDomains'
      SHINGLE_WINDOW: 3
    restart: unless-stopped
    external_links:
      - mongo
    volumes:
      - ./clusterizer/src:/src
      - ./clusterizer/src/shingler:/shingler/shingler

  linkage_analyzer:
    build: ./linkage_analyzer
    container_name: 'linkage_analyzer'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'ClusterizedDomains'
      TOPIC_OUTPUT: 'ProductClusters'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'LabeledDomainClusters'
    restart: unless-stopped
    external_links:
      - mongo
    volumes:
      - ./linkage_analyzer/src:/src

  classifier_page:
    build: classifier_page
    container_name: 'classifier_page'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'ProductClusters'
      TOPIC_OUTPUT: 'ClassifiedProducts'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: '/data/training_set.csv'
      TRAINING_PARQUET: '/data/training_set.snappy.parquet'
      MODEL: '/model/classifier_page.sav'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE_WRITE: 'ClassifiedProducts'
      DATABASE_READ: 'CrawledPages'
    restart: unless-stopped
    external_links:
      - mongo
    volumes:
      - ./classifier_page/src:/src
      - ./classifier_page/data:/data
      - ./classifier_page/model:/model

  xpath_finder:
    build: xpath_finder
    container_name: xpath_finder
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'ClassifiedProducts'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE_WRITE: 'DomainXpaths'
      DATABASE_READ: 'CrawledPages'
    restart: unless-stopped
    external_links:
      - mongo
    volumes:
      - ./xpath_finder/src:/src

networks:
  default:
    external:
      name: environment-network







